name: Deploy to GitHub Pages

on:
  workflow_call:

permissions:
  contents: read

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
